version: '3.9'

services:

  python:
    image: python:3.9
    tty: true
    container_name: python
    volumes:
      - ./python:/app

  node:
    image: node:8-slim
    tty: true
    container_name: node
    volumes: 
      - ./node:/app

  php:
    image: php:8.0-apache
    container_name: php
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example


  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    depends_on:
      - db
      
  redis:
    container_name: redis
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./redisvol:/data

  # phpmyadmin:
  #     image: phpmyadmin
  #     ports:
  #       - 8080:80
  #     environment:
  #       - PMA_HOST=mysql
  #     depends_on:
  #       - mysql

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
